INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17264ec6', 'Tom','Eh','No complaints from Grandpa.', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17264ec6', 'Mary','Its aight','It was dusty when I got it', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17264ec6', 'Wendy','I wanna die','Im so tired of living', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17264ec6', 'Deirdre','Fell Apart','I picked it up and it just fell apart in my hands.', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17264ec6', 'Andrea','Missing pieces','It is missing a few screws and bolts.', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726883c', 'Jack','Assembly required','I dont remember ordering legos', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726883c', 'Irene','Waste of money','it wouldnt turn on at all', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726883c', 'Colin','Im now Bankrupt','Best purchase Ive made, no regrets.', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726883c', 'Dan','Blew Up Somehow','As soon as I turned it on it blew up, now i have no hands. had to use the force to type this', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726883c', 'Matt','Malfunctioned','i think it short circuited', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726a68c', 'Una','Not what I ordered','they accidently sent my a bag of toes', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726a68c', 'Olivia','No Regerts','my husband left me after buying this', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726a68c', 'Peter','Best Product','i think master Skywalker would be proud', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726a68c', 'Emily','Whats Star Wars','I honestly dont know wahat Im doing here', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726a68c', 'Emma','Im homeless','Anybody have a place for me to stay?', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726d116', 'Stephanie','Five Stars','it everything i ever wanted', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726d116', 'Stewart','Too Pricy','the price is too high', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726d116', 'Karen','I took the kids','yup i did it', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726d116', 'Nathan','Never Again','I regret buy it', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1726d116', 'Abigail','Love it','nothing more i can say', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17271b8a', 'Sean','Hate it','worst product ive bought', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17271b8a', 'Dylan','Karen took the kids','she took the f*****g kids', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17271b8a', 'Lauren','Ugh','like omg, like i dont like it', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17271b8a', 'Anthony','Ive seen better','the quality was poor, would not recommend', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17271b8a', 'Simon','Well...','Very disappointing! We named ours Bob, and let me tell you he wasnt the hard working man I was hoping for. Bob spent most of his employment driving from one random side of the house to the other like a junkie looking for his next fix. His actual cleaning was minimal at best and he couldnt find his docking station to save his life. In the next week I had Bob, he never finished a cleaning cycle. One day while at work, the app texted me to say Bob needed my assistance because he was stuck on a cliff. Worried for Bobs safety, I came home to find him passed out in the middle of the dining room rug. That night the family said goodbye to Bob once and for all.', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727634c', 'James','Complete trash','As UPS discretely unloaded my 55 gallon drum of lube, the driver accidentally spilled it into my driveway. Any amount of cars can now fit into the garage.', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727634c', 'Martha','the best','I purchased this book as I was tired of people sitting too near me on public transport.', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727634c', 'Greig','Love it','I am somewhat disappointed. my date still refuses to let me poo on her.', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727634c', 'Zoe','Great','I left this product next to my pet lizard, [but] unfortunately now hes 50 feet tall and is currently destroying Tokyo, Japan.', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727634c', 'Warren','Anybody seen my son?','Im afraid that I have still not had success... No amount of duct tape would keep the cat attached to the saddle while it was on my husbands back', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727c83c', 'Cynthia','Baby Yoda Approves','Champagne? Nah. I ran 18 Bud Lights through this finely tuned, artisan-crafted alcohol bonging device. Whilst on my roof. All in all, if youre trying to get riggity-wrecked with the most class possible, this is just for you', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727c83c', 'Megan','Hate it','Poo-Pourri is a spray that basically lays down a film of scent over the water in your toilet bowl to keep the room from smelling like literal ass.', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727c83c', 'Nicolas','it ok','The insanely sugary intensity of Surge makes Mountain Dew taste like water in comparison. This 90s soda is back to haunt your dreams!', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727c83c', 'Ian','I want another one','I hate my wifes cat but it made my wife pretty happy that the cat can come into our bedroom at-will now and claw the dogs while they sleep. I hate that cat, but his door is pretty cool', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1727c83c', 'John','fell apart','I dont know if this is a scam or if mine was broken, but it doesnt work and I am still getting abducted by UFOs on a regular basis.', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17281350', 'Oliver','gross','Danny Devito now lives in my house', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17281350', 'Angela','WTF','Idk what this is', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17281350', 'Jorge','Inaccurate description','title says it all', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17281350', 'Jonathan','Beautiful','i love the design', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('17281350', 'Ellis','love it','would recommend', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('172834c0', 'Victor','hate it','would not recommend', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('172834c0', 'Justin','a steal','the price is not too bad', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('172834c0', 'Maria','fell apart','not sure if I need to asssemble it or if its supposed to be shattered', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('172834c0', 'Jason','i didnt like it','not a fan of the product', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('172834c0', 'Max','insert title','insert review', 3);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1729b8ea', 'Brandon','nasty','it was cover in some weird slime', 2);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1729b8ea', 'Phteven','broken','didnt work when i tried to use it', 1);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1729b8ea', 'Carol','too small','it didnt fit', 5);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1729b8ea', 'Liam','love it','i love the product', 4);
INSERT INTO user_reviews (id, username, review_title, review, rating) VALUES ('1729b8ea', 'Yvonne','fell apart','im talking about my life here', 3);